POST http://localhost:8000/sendmsg
Content-Type: application/json

{"message": "@explore"}

###

POST http://localhost:8000/connect
Content-Type: application/json

{
  "address": "10.1.1.174",
  "port": 25565
}

###

POST http://localhost:8000/disconnect
Content-Type: application/json

###

# curl "localhost:8000/player"
GET http://localhost:8000/player
Accept: application/json

###

# curl "localhost:8000/chat"
GET http://localhost:8000/chat
Accept: application/json

###