###
POST http://localhost:8000/togglerender

###
POST http://localhost:8000/disconnect

###

POST http://localhost:8000/sendmsg
Content-Type: application/json

{"message": "/tp 0 200 0"}

###

POST http://localhost:8000/connect
Content-Type: application/json

{
  "address": "blazenarchy.net",
  "port": 25565
}

###

# curl "localhost:8000/player"
GET http://localhost:8000/player
Accept: application/json

###

# curl "localhost:8000/chat"
GET http://localhost:8000/chat
Accept: application/json

<> 2020-07-10T045412.200.json

###